from __future__ import annotations

from hashlib import sha256
import json

from src.inspection import (
    INSPECTION_PREDICTION_KIND,
    PREDICTION_RAW_MEASURE_SCALE,
    RAW_MEASURE_KIND,
    InspectionEngine,
    InspectionPrediction,
    LocalArtifactInferenceProvider,
    RawInspectionResult,
)
from src.prototype_ui import (
    DEFAULT_FIXTURE_PATH,
    build_local_provider_demo_projection,
    render_demo_data_javascript,
    write_local_provider_demo_data,
)


FORBIDDEN_KEYS = {
    "accuracy",
    "auc",
    "benchmark",
    "confidence",
    "drift",
    "driftScore",
    "groundTruth",
    "performanceClaim",
    "reviewRouting",
}


def test_projection_uses_local_provider_and_engine_transformation():
    class RecordingProvider:
        def __init__(self) -> None:
            self.predictions: list[InspectionPrediction] = []
            self.inner = LocalArtifactInferenceProvider()

        def predict(self, inspection_input):
            prediction = self.inner.predict(inspection_input)
            self.predictions.append(prediction)
            return prediction

    class RecordingEngine:
        def __init__(self) -> None:
            self.calls: list[tuple[object, InspectionPrediction]] = []
            self.inner = InspectionEngine()

        def inspect(self, inspection_input):  # pragma: no cover
            raise AssertionError("prototype adapter must not call inspect")

        def transform_prediction(self, inspection_input, prediction):
            self.calls.append((inspection_input, prediction))
            return self.inner.transform_prediction(inspection_input, prediction)

    provider = RecordingProvider()
    engine = RecordingEngine()

    projection = build_local_provider_demo_projection(
        provider=provider,
        engine=engine,
    )

    assert len(provider.predictions) == 1
    assert isinstance(provider.predictions[0], InspectionPrediction)
    assert not isinstance(provider.predictions[0], RawInspectionResult)
    assert engine.calls == [(engine.calls[0][0], provider.predictions[0])]
    assert projection["examinationId"] == provider.predictions[0].prediction_id


def test_projection_contains_expected_fixture_result_and_absence_markers():
    projection = build_local_provider_demo_projection()

    assert projection["sourceKind"] == "local_provider_fixture_demo"
    assert projection["inputId"] == "prototype-local-provider-blob-defect"
    assert projection["file"] == "blob_defect.pgm"
    assert projection["artifactUri"] == (
        "tests/fixtures/inspection/blob_defect.pgm"
    )
    assert projection["contentHash"] == _sha256_file(DEFAULT_FIXTURE_PATH)
    assert projection["result"] == "DEFECT"
    assert projection["rawMeasureKind"] == RAW_MEASURE_KIND
    assert projection["rawMeasureScale"] == PREDICTION_RAW_MEASURE_SCALE
    assert projection["rawMeasureValue"] == 75.0
    assert projection["rawText"] == "75.00"
    assert projection["rawBarPercent"] == 75
    assert projection["examinationKind"] == INSPECTION_PREDICTION_KIND
    assert projection["localization"] == {
        "xMin": 0.25,
        "yMin": 0.25,
        "xMax": 0.75,
        "yMax": 0.75,
    }
    assert projection["localizationText"] == "x 0.25-0.75, y 0.25-0.75"
    assert projection["hasLocalization"] is True
    assert projection["calibratedConfidence"] is None
    assert projection["qualifiedOutcome"] is None
    assert projection["calibratedConfidenceStatusText"] == (
        "Calibrated confidence not produced in this prototype slice."
    )
    assert projection["trustStatusText"] == (
        "Trust qualification not run in this prototype slice."
    )
    assert projection["reviewStatusText"] == (
        "No review routing produced in this prototype slice."
    )
    assert projection["evaluationStatusText"] == (
        "No evaluation claim produced in this prototype slice."
    )
    assert projection["visualization"]["imageDataUri"].startswith(
        "data:image/svg+xml"
    )
    assert projection["visualization"]["localizationDataUri"].startswith(
        "data:image/svg+xml"
    )


def test_projection_is_deterministic_and_contains_no_downstream_claim_fields():
    first = build_local_provider_demo_projection()
    second = build_local_provider_demo_projection()

    assert first == second
    assert not (set(_walk_keys(first)) & FORBIDDEN_KEYS)


def test_rendered_javascript_is_deterministic_and_static():
    projection = build_local_provider_demo_projection()

    first = render_demo_data_javascript(projection)
    second = render_demo_data_javascript(projection)

    assert first == second
    assert first.startswith(
        "// Generated by scripts/build_prototype_local_provider_demo.py."
    )
    assert "window.KALIBRA_LOCAL_PROVIDER_DEMO =" in first
    assert str(DEFAULT_FIXTURE_PATH) not in first
    assert "accuracy" not in first
    assert "auc" not in first
    assert "benchmark" not in first
    assert "groundTruth" not in first
    assert '"calibratedConfidence": null' in first


def test_generated_static_data_file_is_byte_stable(tmp_path):
    output_path = tmp_path / "local-provider-demo-data.js"

    first_path = write_local_provider_demo_data(output_path)
    first = first_path.read_text(encoding="utf-8")
    second_path = write_local_provider_demo_data(output_path)
    second = second_path.read_text(encoding="utf-8")

    assert first_path == output_path.resolve()
    assert second_path == output_path.resolve()
    assert first == second
    payload = _extract_payload(first)
    assert payload["file"] == "blob_defect.pgm"
    assert payload["rawText"] == "75.00"
    assert payload["calibratedConfidence"] is None
    assert payload["qualifiedOutcome"] is None


def _sha256_file(path) -> str:
    digest = sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _walk_keys(value):
    if isinstance(value, dict):
        for key, item in value.items():
            yield str(key)
            yield from _walk_keys(item)
    elif isinstance(value, list):
        for item in value:
            yield from _walk_keys(item)


def _extract_payload(source: str):
    prefix = "window.KALIBRA_LOCAL_PROVIDER_DEMO = "
    start = source.index(prefix) + len(prefix)
    payload = source[start:].strip()
    if payload.endswith(";"):
        payload = payload[:-1]
    return json.loads(payload)
