from __future__ import annotations

from hashlib import sha256
import json
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import quote

from src.inspection import (
    InspectionEngine,
    InspectionEngineOutput,
    InspectionPrediction,
    LocalArtifactInferenceProvider,
    RawInspectionResult,
    StabilizedInspectionInput,
)
from src.inspection.local_artifacts import read_pgm_p2


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FIXTURE_PATH = (
    REPO_ROOT / "tests" / "fixtures" / "inspection" / "blob_defect.pgm"
)
DEFAULT_DEMO_OUTPUT_PATH = (
    REPO_ROOT / "assets" / "kalibra-prototype" / "local-provider-demo-data.js"
)
DEMO_INPUT_ID = "prototype-local-provider-blob-defect"
SOURCE_KIND = "local_provider_fixture_demo"


def build_local_provider_demo_projection(
    fixture_path: Path = DEFAULT_FIXTURE_PATH,
    *,
    provider: Any | None = None,
    engine: Any | None = None,
    repo_root: Path = REPO_ROOT,
) -> dict[str, Any]:
    fixture_path = fixture_path.expanduser().resolve()
    repo_root = repo_root.expanduser().resolve()
    artifact_uri = _repo_relative_path(fixture_path, repo_root)
    content_hash = _sha256_file(fixture_path)
    inspection_input = StabilizedInspectionInput(
        input_id=DEMO_INPUT_ID,
        artifact_uri=artifact_uri,
        content_hash=content_hash,
    )

    provider = provider or LocalArtifactInferenceProvider()
    prediction = provider.predict(inspection_input)
    if not isinstance(prediction, InspectionPrediction):
        raise TypeError("prototype provider adapter requires InspectionPrediction")

    engine = engine or InspectionEngine()
    output = engine.transform_prediction(inspection_input, prediction)
    if not isinstance(output, InspectionEngineOutput):
        raise TypeError("prototype provider adapter requires InspectionEngineOutput")

    raw_result = output.raw_inspection_result
    if not isinstance(raw_result, RawInspectionResult):
        raise TypeError("prototype projection requires RawInspectionResult")

    pixels, maxval = read_pgm_p2(fixture_path)
    localization = _localization_projection(raw_result)

    return {
        "sourceKind": SOURCE_KIND,
        "inputId": inspection_input.input_id,
        "file": fixture_path.name,
        "artifactUri": artifact_uri,
        "contentHash": content_hash,
        "inspectionResultId": raw_result.inspection_result_id,
        "inspectionEvidenceRecordId": (
            output.inspection_evidence_record.record_id
        ),
        "examinationId": raw_result.examination_id,
        "examinationKind": raw_result.examination_kind,
        "result": raw_result.judgement.value.upper(),
        "rawMeasureKind": raw_result.raw_measure_kind,
        "rawMeasureScale": raw_result.raw_measure_scale,
        "rawMeasureValue": raw_result.raw_anomaly_measure,
        "rawText": f"{raw_result.raw_anomaly_measure:.2f}",
        "rawBarPercent": _clamp_percent(raw_result.raw_anomaly_measure),
        "localization": localization,
        "localizationText": _localization_text(localization),
        "hasLocalization": localization is not None,
        "calibratedConfidence": None,
        "qualifiedOutcome": None,
        "calibratedConfidenceStatusText": (
            "Calibrated confidence not produced in this prototype slice."
        ),
        "trustStatusText": (
            "Trust qualification not run in this prototype slice."
        ),
        "reviewStatusText": (
            "No review routing produced in this prototype slice."
        ),
        "evaluationStatusText": (
            "No evaluation claim produced in this prototype slice."
        ),
        "visualization": _visualization_projection(
            pixels,
            maxval,
            localization,
        ),
    }


def render_demo_data_javascript(projection: Mapping[str, Any]) -> str:
    payload = json.dumps(
        projection,
        indent=2,
        sort_keys=True,
        separators=(",", ": "),
    )
    return (
        "// Generated by scripts/build_prototype_local_provider_demo.py.\n"
        "// Static prototype data only; not a trust, review, or evaluation record.\n"
        f"window.KALIBRA_LOCAL_PROVIDER_DEMO = {payload};\n"
    )


def write_local_provider_demo_data(
    output_path: Path = DEFAULT_DEMO_OUTPUT_PATH,
    *,
    fixture_path: Path = DEFAULT_FIXTURE_PATH,
) -> Path:
    projection = build_local_provider_demo_projection(fixture_path)
    output_path = output_path.expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_demo_data_javascript(projection),
        encoding="utf-8",
    )
    return output_path


def _repo_relative_path(path: Path, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _localization_projection(
    raw_result: RawInspectionResult,
) -> dict[str, float] | None:
    if raw_result.localization is None:
        return None
    region = raw_result.localization.region
    return {
        "xMin": region.x_min,
        "yMin": region.y_min,
        "xMax": region.x_max,
        "yMax": region.y_max,
    }


def _localization_text(localization: Mapping[str, float] | None) -> str:
    if localization is None:
        return "not present"
    return (
        f"x {localization['xMin']:.2f}-{localization['xMax']:.2f}, "
        f"y {localization['yMin']:.2f}-{localization['yMax']:.2f}"
    )


def _clamp_percent(value: float) -> int:
    return max(0, min(100, int(round(value))))


def _visualization_projection(
    pixels: list[list[int]],
    maxval: int,
    localization: Mapping[str, float] | None,
) -> dict[str, Any]:
    height = len(pixels)
    width = len(pixels[0])
    return {
        "width": width,
        "height": height,
        "imageDataUri": _pgm_svg_data_uri(pixels, maxval, None),
        "localizationDataUri": _pgm_svg_data_uri(pixels, maxval, localization),
    }


def _pgm_svg_data_uri(
    pixels: list[list[int]],
    maxval: int,
    localization: Mapping[str, float] | None,
) -> str:
    height = len(pixels)
    width = len(pixels[0])
    rects: list[str] = []
    for y, row in enumerate(pixels):
        for x, value in enumerate(row):
            shade = round((value / maxval) * 255)
            rects.append(
                f'<rect x="{x}" y="{y}" width="1" height="1" '
                f'fill="rgb({shade},{shade},{shade})"/>'
            )

    overlay = ""
    if localization is not None:
        x = localization["xMin"] * width
        y = localization["yMin"] * height
        overlay_width = (localization["xMax"] - localization["xMin"]) * width
        overlay_height = (localization["yMax"] - localization["yMin"]) * height
        overlay = (
            f'<rect x="{x:.6g}" y="{y:.6g}" '
            f'width="{overlay_width:.6g}" height="{overlay_height:.6g}" '
            'fill="#e5514e" fill-opacity="0.22" '
            'stroke="#e5514e" stroke-width="0.08"/>'
        )

    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        'shape-rendering="crispEdges">'
        '<rect width="100%" height="100%" fill="#070a0e"/>'
        f'{"".join(rects)}{overlay}'
        "</svg>"
    )
    # Keep the data: URI valid as an `<img src>` and inside an unquoted CSS
    # `url(...)` embedded in an inline `style="..."`:
    #   - omit `;charset=utf-8` so the only `;` (a CSS declaration separator)
    #     cannot truncate the value when used in an inline style;
    #   - `#` would start a URI fragment (truncating the SVG at the first
    #     fill="#...") and `%` (from width="100%") would break percent-decoding;
    #   - `(`/`)` (from `rgb(...)` fills) would close an unquoted CSS `url()`.
    # Encoding those keeps the projection renderable in every context.
    return "data:image/svg+xml," + quote(svg, safe=":/,=")
